// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcAjSj0puzcpDuKiEwYcN5yoEqUzdQ5UA',
    appId: '1:517815203629:web:4f315e13d6c9cd8b37c5a4',
    messagingSenderId: '517815203629',
    projectId: 'online-shop-dcbc6',
    authDomain: 'online-shop-dcbc6.firebaseapp.com',
    storageBucket: 'online-shop-dcbc6.appspot.com',
    measurementId: 'G-6JJXE8PHW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDygqdz8uoHFjrUeFiypG1PvfgkwNMmiW0',
    appId: '1:517815203629:android:3f172e2ed8d5dca437c5a4',
    messagingSenderId: '517815203629',
    projectId: 'online-shop-dcbc6',
    storageBucket: 'online-shop-dcbc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJtT14KjatdZHLMPBiZRSXQluQLBbG6fU',
    appId: '1:517815203629:ios:a5f9fd26a02a349437c5a4',
    messagingSenderId: '517815203629',
    projectId: 'online-shop-dcbc6',
    storageBucket: 'online-shop-dcbc6.appspot.com',
    androidClientId: '517815203629-crjgopm0r8o696kjhabgk4qg9nltk2aj.apps.googleusercontent.com',
    iosClientId: '517815203629-tgl55af7bn1kr8o9mrfioqh00qbab6vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJtT14KjatdZHLMPBiZRSXQluQLBbG6fU',
    appId: '1:517815203629:ios:a5f9fd26a02a349437c5a4',
    messagingSenderId: '517815203629',
    projectId: 'online-shop-dcbc6',
    storageBucket: 'online-shop-dcbc6.appspot.com',
    androidClientId: '517815203629-crjgopm0r8o696kjhabgk4qg9nltk2aj.apps.googleusercontent.com',
    iosClientId: '517815203629-tgl55af7bn1kr8o9mrfioqh00qbab6vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD79vEmkUURHqdXWGZptarUXZYAE2PmOX0',
    appId: '1:517815203629:web:0ae98f49dbada6a437c5a4',
    messagingSenderId: '517815203629',
    projectId: 'online-shop-dcbc6',
    authDomain: 'online-shop-dcbc6.firebaseapp.com',
    storageBucket: 'online-shop-dcbc6.appspot.com',
    measurementId: 'G-JB26SKYG37',
  );
}
